### PR TITLE
Changes all extraction paths to use Unix-style path string.

### LINKED ISSUE #74: build failure on windows
**Description of the issue**:
error after running jib:build with no gcr cred helper installed
**Expected behavior**:
a helpful message explaining I didn't have cred helper configured properly
**Steps to reproduce**: 
checkout https://github.com/patflynn/kplay/tree/jib-based
run `mvn jib:build`
**Environment**: 
C:\Users\patrick\Projects\kplay\spring-boot-basic>mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: C:\Users\patrick\Tools\apache-maven-3.3.9\bin\..
Java version: 9.0.1, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk-9.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**`jib-maven-plugin` Configuration:**
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**Log output**: 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.129 s
[INFO] Finished at: 2018-02-07T15:50:53-05:00
[INFO] Final Memory: 23M/78M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.1.0:build (default-cli) on project demo-app: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:0.1.0:build failed: Illegal char <*> at index 0: * -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.1.0:build (default-cli) on project demo-app: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:0.1.0:build fail
ed: Illegal char <*> at index 0: *
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:0.1.0:build failed: Illegal char <*> at index 0: *
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 0: *
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.resolve(Path.java:402)
        at com.google.cloud.tools.jib.builder.BuildImageSteps.getEntrypoint(BuildImageSteps.java:175)
        at com.google.cloud.tools.jib.builder.BuildImageSteps.run(BuildImageSteps.java:127)
        at com.google.cloud.tools.jib.maven.BuildImageMojo.buildImage(BuildImageMojo.java:157)
        at com.google.cloud.tools.jib.maven.BuildImageMojo.execute(BuildImageMojo.java:142)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]

**Additional Information**:

### PR DESCRIPTION
**Pull request by coollog**
Fixes #74

### CODE REVIEW

**Comment by coollog** [comment]
@patflynn Hey patrick, could you see if this PR fixes the windows build error you encountered?

You'll have to:

```commandline
git clone https://github.com/google/jib.git
git checkout entrypoint-windows
cd jib-maven-plugin
./mvnw install
```

Then, change the jib-maven-plugin version in your test project to `0.1.1-SNAPSHOT`.

**Comment by patflynn** [comment]
@coollog can the windows kokoro build not catch this?

would it make more sense to keep using Path (for safety) until it's rendered and to convert to unix path at that point?
@loosebazooka

**Comment by coollog** [comment]
The Kokoro Windows build doesn't catch this right now because running the full build process is in the integration tests, which requires Docker, among other dependencies, to run. We need to make sure the Kokoro environment works fully before enabling integration tests. #11 is the issue regarding this.

**Comment by loosebazooka** [comment]
Yeah we looked around, but Path is by nature tied to the underlying OS, we'd have to do some shenanigans to force it to give us Unix paths (which feels more error prone). We might as well just define strings, we're not really passing this param around.

**Comment by patflynn** [comment]
that appears to have done the trick. 

I now get `[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.1.1-SNAPSHOT:build (default-cli) on project demo-app: Build image failed: Cannot run program "docker-credential-gcr": CreateProcess error=2, The system cannot find the file specified -> [Help 1]
`

Which is what I expected because I don't have a cred helper installed.

**Pull request merged**
